global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
