apiVersion: 1

datasources:
  - name: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      timeout: 60
      maxLines: 1000
      derivedFields:
        - name: traceID
          datasourceUid: 'jaeger'
          matcherType: label
          matcherRegex: trace_id
          url: "$${__value.raw}"

  - name: prometheus
    type: prometheus
    access: proxy
    editable: true
    url: http://prometheus:9090

  - name: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: true
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{service_name="App"} | trace_id="$${__trace.traceId}"'
